config/routes.rb
Rails.application.routes.draw do
  resources :stores do
  resource :items
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :store
end

app/models/store.rb
class Store < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  class ItemsController < ApplicationController
    before_action :set_store
    before_action :set_topic,  only: [:show, :edit, :update, :destroy]
    
    def index
      @items = @store.items
    end
  
    def show
      
    end
  
    def new
      @item = @stores[:id].items.new()
      render partial: "form"
    end
  
    def create
     @item =@store.items.new(item_params)
  
      if @item.save
        redirect_to store_items_path(@store)
      else
        render :new
      end
    end
  
    def edit
      render partial: "form"
    end
  
    def update
      if @item.update(item_params)
        redirect_to store_items_path(@store, @item)
      else
        render :edit
      end
    end
  
    def destroy
      @item.destroy
      redirect_to store_items_path(@store)
    end
  
    private
      def set_store
        @store = Store.find(params[:store_id])
      end
       
      def set_topic
        @item = item.find(params[:id])
       end
  
      def topic_params
        params.require(:item).permit(:name, :body) 
      end
  end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only:[:show, :edit, :update, :destroy]
  # before_action :set_store, exclude: [:index, :new, :create]
  
  def index
    @store = store.index
  end

  def show
    # render :seed
  end

  def edit
    render partial:"form"
  end

  def  create
    @store = Store.new (store_params)

    if @store.save
      redirect_to store_path
    else
      render :new
    end
  end

  def update
    @store =Store.find()
    if @store.update(store_params)
      redirect_to store_path(@store)
    else
      render :edit
    end
  end

  def destroy
    
  
  
  private
  def store_params
    params.require(:store).permit(:name)
  end
      
  def set_store @store = Store.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<h1>Click an Item Baller!</h1>
<%= link_to 'Create a new item', new_store_idea_path(@store) %>
<ul>
  <% @items.each do |item| %>
    <li><%= link_to topic.name, [@store, topic] %></li>
  <% end %>
</ul>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<%= link_to "View Items", stores_items_path(@store) %>
<br />
<%= link_to "Edit Store", edit_store_path(@store) %>
<br />
<%= link_to "Delete Store", store_path(@store), method:delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Department</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stores/_form.html.erb
<h1><%= @store.id ? "Edit Store" : "New Store"%></h1>
<hr />
<%= form_for @store do |f| %>
<$= f.label :name %>
<%= f.text_field :name, required: true, autofocus: true %>

<%= f.submit %>
<%= end %>

app/views/stores/edit.html.erb
<h1>Stores#edit</h1>
<p>Find me in app/views/stores/edit.html.erb</p>

app/views/stores/index.html.erb
<h1>Click a Store to view content</h1>
<%= link_to "Create a new store", new_store_path%>

<h3><%= @stores.lenght === 0 ? "No Stores Added" : ""%></h3>

<ul>
<% @stores.each do |store|%>
  <li><%= link_to store.name, store_path(store) %%></li>
  
  <% end %>
  </ul>

app/views/stores/new.html.erb
<h1>Stores#new</h1>
<p>Find me in app/views/stores/new.html.erb</p>

app/views/stores/show.html.erb
<H1><%= @store .name%></h1>
<hr />
<p>Whatwould you like to do?</p>
<%= link_to "View Topics", stores_topics_path(@sub) %>
<br />
<%= link_to "Edit Store", edit_store_path(@sub) %>
<br />
<%= link_to "Delete Store", store_path(@sub), method:delete %>